server:
  context-path: /springboot1
  port: 8888
mybatis:
  mapper-locations: com/baizhi/mapper/*Mapper.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/novel
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123